power<-read.table("household_power_consumption.txt",stringsAsFactors = FALSE, header = TRUE, sep = ";")
tail(power)
global<-subset(power, Date =="1/2/2007" | Date == "2/2/2007")
par(mfrow = c(2,2),mar = c(2,4,0,2), oma = c(0,0,2,1))
DateTime2<-strptime(paste(global$Date,global$Time,sep= ""),"%d/%m/%Y %H:%M:%S")
with(global,plot(DateTime2,Global_active_power,ylab ="Global Active Power",type = "l",xlab = ""))
with(global,plot(DateTime2,Voltage,ylab ="Voltage",type = "l",xlab = ""))
sub_metering_1<-as.numeric(global$Sub_metering_1)
sub_metering_2<-as.numeric(global$Sub_metering_2)
sub_metering_3<-as.numeric(global$Sub_metering_3)
with(global,plot(DateTime2,sub_metering_1,type ="l",xlab="",ylab="Energy sub metering"))
lines(sub_metering_2~Datetime1,col="Red")
lines(sub_metering_3~Datetime1,col="Blue")
legend("topright",col=c("black","red","blue"),lty = 1, lwd =1,bty ="n",legend=c("Sub_metering_1","Sub_metering_2","Sub_metering_3"))
with(global,plot(DateTime2,Global_reactive_power,ylab ="Global Reactive Power",type = "l",xlab = ""))       
dev.copy(png,file="plot4.png",width = 480, height = 480)
dev.off()
